AWSTemplateFormatVersion: "2010-09-09"
Description: "ActiveSG Micro Services Code Pipeline"

Parameters:

  ### Codepipeline Parameters ###
  GitHubUserName:
    Type: String
    Description: "GitHub username for the repository"

  GitHubRepository:
    Type: String
    Description: "GitHub repository"

  GitHubBranch:
    Type: String
    Description: "GitHub Branch"
    Default: master

  GitHubOAuthToken:
    Type: String
    Description: "GitHub Token"
    NoEcho: true

  S3ArtifactStoreBucketName:
    Type: String
    Description: "S3 bucket for the artifact store"

  ### ActiveSG Parameters ###
  S3PDFBucketName:
    Type: String
    Description: "S3 Bucket name for the generated PDF."

  AndroidSNSArn:
    Type: String
    Description: "SNS Amazon Resource Name for android application"

  iOSSNSArn:
    Type: String
    Description: "SNS Amazon Resource Name for iOS application"

  MessageBirdAccessKey:
    Type: String
    Description: "Message Bird Access Key"
    NoEcho: true

Resources:
  S3ArtifactStoreBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${S3ArtifactStoreBucketName}-${AWS::Region}"
      AccessControl: "Private"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  S3PDFBucketNameParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "S3 Bucket name for the generated PDF."
      Name: "S3PDFBucketName"
      Type: String
      Value: !Ref S3PDFBucketName

  AndroidSNSArnParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "SNS Amazon Resource Name for android application"
      Name: "AndroidSNSArn"
      Type: String
      Value: !Ref AndroidSNSArn

  iOSSNSArnParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "SNS Amazon Resource Name for iOS application"
      Name: "iOSSNSArn"
      Type: String
      Value: !Ref iOSSNSArn

  MessageBirdAccessKeyParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Message Bird Access Key"
      Name: "MessageBirdAccessKey"
      Type: String
      Value: !Ref MessageBirdAccessKey

  CodeBuildLambda:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: "Code Build for ActiveSG Micro services"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: "aws/codebuild/standard:2.0"
        EnvironmentVariables:
          - Name: ARTIFACT_BUCKET
            Value: !Ref S3ArtifactStoreBucket

      ServiceRole: !GetAtt CodeStarServiceRole.Arn
      Source:
        Type: CODEPIPELINE

  WebHook:
    Type: "AWS::CodePipeline::Webhook"
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubOAuthToken
      Filters:
        - JsonPath: "$.ref"
          MatchEquals: "refs/heads/{Branch}"
      Name: "ActiveSGServicesCodePipelineWebHook"
      TargetAction: "GitHub-Source-Action"
      TargetPipeline: !Ref ActiveSGServicesCodePipeline
      TargetPipelineVersion: 1

  ActiveSGServicesCodePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties: 
      ArtifactStore: 
        Location: !Ref S3ArtifactStoreBucket
        Type: "S3"
      Name: "ActiveSG"
      RoleArn: !GetAtt CodeStarServiceRole.Arn
      Stages: 
        - Name: "GitHub-Source"
          Actions:
            - Name: "GitHub-Source-Action"
              ActionTypeId:
                Category: "Source"
                Owner: "ThirdParty"
                Version: 1
                Provider: "GitHub"
              OutputArtifacts:
                - Name: "SourceCode"
              Configuration:
                Owner: !Ref GitHubUserName
                Repo: !Ref GitHubRepository
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubOAuthToken
                # PollForSourceChanges: false
        - Name: "Build"
          Actions:
            - Name: "Build-Action"
              ActionTypeId:
                Category: "Build"
                Owner: "AWS"
                Version: 1
                Provider: "CodeBuild"
              InputArtifacts:
                - Name: "SourceCode"
              OutputArtifacts:
                - Name: "Template"
              Configuration:
                ProjectName: !Ref CodeBuildLambda
        - Name: "Deploy"
          Actions:
            - Name: "Deploy-Action"
              InputArtifacts:
                - Name: "Template"
              ActionTypeId:
                Category: "Deploy"
                Owner: "AWS"
                Version: 1
                Provider: "CloudFormation"
              Configuration:
                StackName: !Sub "active-sg-micro-services-deployment-${AWS::Region}"
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !GetAtt CodeStarServiceRole.Arn
                TemplatePath: "Template::activeSg_sam_output.yaml"

  CodeStarServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: 
                - "codepipeline.amazonaws.com"
                - "codebuild.amazonaws.com"
                - "cloudformation.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "codestar-policies"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: 
                  - "logs:*"
                  - "codebuild:*"
                  - "codedeploy:*"
                  - "cloudformation:*"
                  - "iam:PassRole"
                  - "iam:GetRole"
                  - "iam:AttachRolePolicy"
                  - "iam:CreateRole"
                  - "iam:PutRolePolicy"
                  - "iam:DeleteRolePolicy"
                  - "iam:DeleteRole"
                  - "s3:*"
                  - "sqs:*"
                  - "lambda:*"
                  - "ssm:GetParameters"
                Resource: "*"