version: 0.2
phases:
  
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - echo installing dependency.........
      - cd active_sg_notification && npm install
      - cd ../pdf_generator && npm install
      - cd ../pdf_notification && npm install
      - cd ../
      - aws cloudformation package --template-file activeSg_sam.yaml --s3-bucket ${ARTIFACT_BUCKET} --output-template-file activeSg_sam_output.yaml --debug
      - export REVISION="revisionType=S3,s3Location{bucket=${ARTIFACT_BUCKET},key=activeSg_sam_output.yaml,bundleType=YAML}"
      - aws deploy create-deployment \
          --application-name=${APPLICATION_NAME} \
          --deployment-group-name=${DEPLOYMENT_GROUP_NAME} \ 
          --revision=$REVISION \
          --deployment-config-name='CodeDeployDefault.LambdaCanary10Percent30Minutes'
artifacts:
  type: zip
  files:
    # - active_sg_notification/*
    # - pdf_generator/*
    # - pdf_notification/*
    - activeSg_sam.yaml
    - activeSg_sam_output.yaml