version: 0.2
phases:
  
  install:
    runtime-versions:
      nodejs: 8.10
    commands:
      - echo installing dependency.........
      - cd active_sg_notification && npm install
      - cd ../pdf_generator && npm install
      - cd ../pdf_notification && npm install

  build:
    commands:
      - aws cloudformation package --template-file activeSg_sam.yaml --s3-bucket $BUCKET --output-template-file activeSg_sam_output.yaml --debug

artifacts:
  type: zip
  files:
    - active_sg_notification/*
    - pdf_generator/*
    - pdf_notification/*
    - activeSg_sam_output.yml