version: 0.2
phases:
  install:
    commands:
      - cd active_sg_notification && npm install
      - cd pdf_generator && npm install
      - cd pdf_notification && npm install

  build:
    commands:
      - aws cloudformation package --template-file activeSg_sam.yaml --s3-bucket $BUCKET --output-template-file activeSg_sam_output.yaml --debug

artifacts:
  type: zip
  files:
    - active_sg_notification/node_modules/nodemailer/*
    - pdf_generator/node_modules/html-pdf/*
    - pdf_notification/node_modules/nodemailer/*
    - activeSg_sam_output.yml